

development:
  adapter: postgresql
  encoding: unicode
  database: piglatin_development
  pool: 5
  username: piglatin
  password: password1

test:
  adapter: postgresql
  encoding: unicode
  database: piglatin_test
  pool: 5
  username: piglatin
  password: password1

production:
  adapter: postgresql
  encoding: unicode
  database: piglatin_prod
  pool: 5
  username: piglatin
  password: password1
  host: postgresql-elliptical-61967
